/**
 * БАЗА ВОПРОСОВ (Перераспределенная)
 * Всего: 131 вопрос.
 * Разбиение: 4 варианта по ~33 вопроса.
 */
const questionsDB = [
    // --- ВАРИАНТ 1 (33 вопроса) ---
    { v: 1, q: "In a storage controller, what is a cache?", o: ["A power supply unit", "A memory chip on the disk controller that buffers data between internal storage and external interfaces", "A network switch", "A dedicated flash disk for logs"], a: [1] },
    { v: 1, q: "The earliest form of external storage is:", o: ["Cloud storage", "NVMe", "JBOD", "SSD"], a: [2] },
    { v: 1, q: "Internal storage is typically located:", o: ["Remote data center", "On network appliances", "Inside the host", "Inside a cloud pool"], a: [2] },
    { v: 1, q: "The disk enclosure uses a modular design so that components such as expansion modules and power modules can be replaced in the field.", o: ["True", "False"], a: [0] },
    { v: 1, q: "Which components belong to a NAS device? (Choose TWO)", o: ["Monitor", "Keyboard", "NIC", "CPU", "Memory"], a: [3, 4] },
    { v: 1, q: "Early flash SSDs were based on:", o: ["Quantum wells", "Floating gate transistor", "Optical media", "Graphene"], a: [1] },
    { v: 1, q: "Each disk platter in an HDD has two read/write heads to read and write data on both surfaces of the platter.", o: ["True", "False"], a: [0] },
    { v: 1, q: "Which disk enclosure indicator shows that an alarm has been reported?", o: ["Blinking blue", "Steady green", "Off", "Steady yellow (amber)"], a: [3] },
    { v: 1, q: "Which design practice improves power reliability for disk enclosures?", o: ["Single large PSU", "BBUs instead of power modules", "No redundancy", "Connecting power modules to different PDUs"], a: [3] },
    { v: 1, q: "Cloud storage relies on:", o: ["Local-only access", "Only HDD media", "Multi-tenant virtualized infrastructure", "Tape-based I/O"], a: [2] },
    { v: 1, q: "Which modules are typically included in a controller enclosure design? (Select one or more)", o: ["Controllers with fans", "BBUs and power modules", "Management and interface modules", "System subrack"], a: [0, 1, 2, 3] },
    { v: 1, q: "Which components are part of a typical disk enclosure design? (Select one or more)", o: ["Expansion modules", "System subrack", "Disks", "Power modules"], a: [0, 1, 2, 3] },
    { v: 1, q: "What is the function of the system subrack backplane?", o: ["Manages service ports", "Converts protocols", "Stores cache", "Integrates signal and power connectivity among modules"], a: [3] },
    { v: 1, q: "What does a Cache flush do?", o: ["Writes data from cache to disk", "Clears cache without saving", "Reads data from disk to cache", "Encrypts cache data"], a: [0] },
    { v: 1, q: "Emerging storage media include: (Select one or more)", o: ["Floppy disks", "Atomic storage", "DNA storage", "Quantum storage"], a: [1, 2, 3] },
    { v: 1, q: "Modern storage trends include: (Select one or more)", o: ["Manual expansion", "Intelligence", "All-flash", "Cloudification"], a: [1, 2, 3] },
    { v: 1, q: "Memory-centric architecture is enabled by:", o: ["RAID 0", "JSON", "HTML", "Memory Fabric"], a: [3] },
    { v: 1, q: "RAID 10 provides:", o: ["Compression", "High performance", "Mirroring", "Striping", "No redundancy"], a: [1] },
    { v: 1, q: "RAID 10 is a combination of:", o: ["RAID 0 + RAID 0", "RAID 1 + RAID 0", "RAID 6 + RAID 0", "RAID 5 + RAID 0"], a: [1] },
    { v: 1, q: "Which RAID level uses distributed parity?", o: ["RAID 1", "RAID 10", "RAID 0", "RAID 3", "RAID 5"], a: [4] },
    { v: 1, q: "Which RAID evolution technique distributes data blocks across all disks?", o: ["Block virtualization", "Parity mapping", "Disk mirroring", "LUN virtualization"], a: [0] },
    { v: 1, q: "Which properties are improved by RAID-TP?", o: ["Capacity utilization", "Reliability", "Cache size", "File indexing"], a: [1] },
    { v: 1, q: "Components of RAID 2.0+ include: (Select one or more)", o: ["Chunk Group", "NIC", "Disk Group", "Disk Domain", "CPU Cache"], a: [0, 3] },
    { v: 1, q: "RAID 5 tolerates two disk failures.", o: ["True", "False"], a: [1] },
    { v: 1, q: "RAID 1 primarily provides:", o: ["Low cost", "High speed", "High capacity", "Data compression", "High reliability"], a: [4] },
    { v: 1, q: "Which RAID level eliminates write penalty in random writes?", o: ["RAID 5", "RAID 10", "RAID 6", "RAID 0"], a: [1] },
    { v: 1, q: "RAID 6 requires at least how many disks?", o: ["N+2", "N+3", "2", "4"], a: [3] },
    { v: 1, q: "Which RAID level offers the best performance but no redundancy?", o: ["RAID 3", "RAID 5", "RAID 1", "RAID 0", "RAID 10"], a: [3] },
    { v: 1, q: "How many disk failures can RAID 6 tolerate?", o: ["0", "1", "2", "3"], a: [2] },
    { v: 1, q: "What is the smallest unit for migration in RAID 2.0+?", o: ["LUN", "Chunk", "Grain", "Extent", "Stripe"], a: [3] },
    { v: 1, q: "What causes the write penalty in RAID 3 and RAID 5?", o: ["Cache flushing", "Disk encryption", "Parity calculation", "Network traffic"], a: [2] },
    { v: 1, q: "Grains are used in:", o: ["Disk groups", "Volumes", "Disk domains", "Thin LUNs", "Thick LUNs"], a: [3] },
    { v: 1, q: "What forms a Chunk Group (CKG)?", o: ["Parity disks", "LUNs", "Volumes", "Chunks from different disks", "Hot spare disks"], a: [3] },

    // --- ВАРИАНТ 2 (33 вопроса) ---
    { v: 2, q: "What is the main purpose of RAID?", o: ["Encrypt data", "Improve performance and data reliability", "Increase network speed", "Reduce storage cost"], a: [1] },
    { v: 2, q: "RAID 1 (mirroring) stores duplicate copies. Efficiency is:", o: ["100%", "50%", "33%", "75%"], a: [1] },
    { v: 2, q: "RAID 6 uses dual parity.", o: ["True", "False"], a: [0] },
    { v: 2, q: "For critical data with large disks, the recommended RAID level is:", o: ["RAID 0", "RAID 5", "RAID 6", "RAID 1"], a: [2] },
    { v: 2, q: "RAID-TP (Triple Parity) allows tolerance of how many failures?", o: ["1", "2", "3", "4"], a: [2] },
    { v: 2, q: "RAID 2.0+ uses a many-to-many reconstruction approach.", o: ["True", "False"], a: [0] },
    { v: 2, q: "Which protocol is mainly used by NAS in Linux?", o: ["NFS", "CIFS", "FTP", "HTTP"], a: [0] },
    { v: 2, q: "NFS is a stateful protocol.", o: ["True", "False"], a: [1] },
    { v: 2, q: "Which protocol is based on SMB?", o: ["FTP", "HTTP", "CIFS", "NDMP", "NFS"], a: [2] },
    { v: 2, q: "SAS architecture layers include: (Select one or more)", o: ["Application", "Network", "Phy", "Physical", "Link"], a: [0, 2, 3, 4] },
    { v: 2, q: "The statement 'iSCSI carries SCSI commands over IP' is:", o: ["True", "False"], a: [0] },
    { v: 2, q: "Which protocol is designed for high-speed storage networks?", o: ["SATA", "CIFS", "NFS", "USB", "Fibre Channel (FC)"], a: [4] },
    { v: 2, q: "What does SCSI stand for?", o: ["Smart Computer System Interface", "Secure Computer Storage Interface", "Small Computer System Interface", "Serial Computer System Interface"], a: [2] },
    { v: 2, q: "Which iSCSI initiator has the highest performance?", o: ["Software initiator", "USB adapter", "TOE NIC", "iSCSI HBA", "Ethernet NIC"], a: [3] },
    { v: 2, q: "What is a LUN?", o: ["A file unit", "A disk controller", "A logical storage unit", "A parity block"], a: [2] },
    { v: 2, q: "How many main layers does FC protocol have?", o: ["5", "6", "3", "4", "7"], a: [0] },
    { v: 2, q: "Which protocol carries SCSI commands over IP?", o: ["SAS", "FC", "FCoE", "iSCSI", "NVMe"], a: [3] },
    { v: 2, q: "What is the external representation of a volume?", o: ["Chunk", "Grain", "Storage pool", "LUN", "Disk group"], a: [3] },
    { v: 2, q: "Which technology allows FC to work over Ethernet?", o: ["SAS", "PCIe", "FCoE", "RDMA", "NVMe"], a: [2] },
    { v: 2, q: "Which RAID level uses distributed parity?", o: ["RAID 3", "RAID 5", "RAID 0", "RAID 10", "RAID 1"], a: [1] },
    { v: 2, q: "What does iSCSI use to transmit data?", o: ["FC", "TCP/IP", "SAS", "UDP", "RDMA"], a: [1] },
    { v: 2, q: "In SCSI, who sends requests?", o: ["Target", "Switch", "Initiator", "LUN", "Controller"], a: [2] },
    { v: 2, q: "Which FC port connects devices to the fabric?", o: ["G_Port", "F_Port", "U_Port", "NL_Port", "E_Port"], a: [1] },
    { v: 2, q: "What does SAS stand for?", o: ["Smart Access Storage", "Server Attached Storage", "Serial Attached SCSI", "System Access Standard"], a: [2] },
    { v: 2, q: "What processes SCSI commands?", o: ["Initiator", "Server", "HBA", "Target", "Cache"], a: [3] },
    { v: 2, q: "What main advantage does SAS have over parallel SCSI?", o: ["Encryption", "Simpler protocol", "Higher speed and reliability", "Lower power use"], a: [2] },
    { v: 2, q: "Which FC topology is similar to Ethernet switching?", o: ["Fabric", "Point-to-Point", "FC-AL", "Bus", "Ring"], a: [0] },
    { v: 2, q: "NVMe is optimized for:", o: ["HDD", "Tape", "Flash storage (SSD)", "Optical disks"], a: [2] },
    { v: 2, q: "PCIe advantages include: (Select one or more)", o: ["Error detection", "High bandwidth", "Hot swap (native)", "Long distance"], a: [0, 1] },
    { v: 2, q: "Which process occurs first in SmartMigration?", o: ["Service data synchronization", "Pair splitting", "Cache flush", "LUN information exchange", "Consistency check"], a: [0] },
    { v: 2, q: "What is snapshot cascading?", o: ["Snapshot encryption", "Deleting old snapshots", "Creating child snapshots that include parent data", "Merging snapshots"], a: [2] },
    { v: 2, q: "Which two operations are controlled by consistency groups?", o: ["Compression", "Splitting", "Snapshot", "Synchronization", "Encryption"], a: [1, 3] },
    { v: 2, q: "What happens in snapshot rollback?", o: ["Data is restored to snapshot time", "Data is deleted", "Storage is reinitialized", "Cache is flushed"], a: [0] },

    // --- ВАРИАНТ 3 (33 вопроса) ---
    { v: 3, q: "Which three industries benefit most from HyperMetro?", o: ["Healthcare", "Social security", "Retail", "Finance", "Gaming", "Entertainment"], a: [0, 1, 3] },
    { v: 3, q: "Which two synchronization types exist in HyperClone?", o: ["Full", "Snapshot", "Offline", "Incremental", "Mirror"], a: [0, 3] },
    { v: 3, q: "HyperMetro ensures RPO = ? and RTO = ?", o: ["0, 0", "1, 1", "0, 5", "5, 0"], a: [0] },
    { v: 3, q: "SmartQoS assigns priorities based on:", o: ["Disk model", "User account", "LUN / file system", "Encryption type", "Server IP"], a: [2] },
    { v: 3, q: "Which algorithm is used in SmartCompression?", o: ["AES", "SHA-1", "MD5", "LZ77", "RSA"], a: [3] },
    { v: 3, q: "Which three HyperMetro properties improve reliability?", o: ["RAID TP", "Quorum arbitration", "Snapshot compression", "Dual-write", "Locking", "Encryption"], a: [1, 3, 4] },
    { v: 3, q: "In HyperMetro both data centers can carry services simultaneously.", o: ["True", "False"], a: [0] },
    { v: 3, q: "What records data changes in HyperClone?", o: ["RAID table", "Mapping file", "Cache table", "Snapshot index", "Differential bitmap"], a: [4] },
    { v: 3, q: "HyperSnap snapshots are full physical copies.", o: ["True", "False"], a: [1] },
    { v: 3, q: "Which two communication methods are supported in HyperMetro?", o: ["Fibre Channel", "IP network", "USB", "NFC", "Bluetooth"], a: [0, 1] },
    { v: 3, q: "Which two SmartTier phases handle data movement/placement decisions?", o: ["RAID rebuild", "Data migration", "Data placement analysis", "I/O monitoring", "Cache flush"], a: [1, 2] },
    { v: 3, q: "Inline deduplication performs deduplication:", o: ["After writing data", "During backup", "After migration", "Before writing data", "During replication"], a: [3] },
    { v: 3, q: "Which two components are involved in a SmartMigration pair?", o: ["Disk", "File system", "Source LUN", "Target LUN", "Server"], a: [2, 3] },
    { v: 3, q: "HyperReplication pairs require both LUNs to be in the same storage system.", o: ["True", "False"], a: [1] },
    { v: 3, q: "Which component monitors data access in SmartTier?", o: ["Snapshot manager", "Data migration module", "RAID engine", "I/O monitoring module", "Cache engine"], a: [3] },
    { v: 3, q: "Which three phases exist in SmartTier?", o: ["Snapshot", "Data migration", "Compression", "Data analysis", "I/O monitoring", "Encryption"], a: [1, 3, 4] },
    { v: 3, q: "Which two SmartQoS mechanisms exist?", o: ["Snapshot control", "Encryption control", "I/O priority scheduling", "Cache balancing", "I/O traffic control"], a: [2, 4] },
    { v: 3, q: "SmartQoS dynamically allocates which resource?", o: ["CPU threads", "Storage system resources", "Network packets", "Snapshots", "Encryption keys"], a: [1] },
    { v: 3, q: "What is the role of a secondary site in HyperReplication?", o: ["Cache storage", "Logging only", "Backup and service takeover", "Performance tuning"], a: [2] },
    { v: 3, q: "HyperClone allows reading and writing to target LUN during synchronization.", o: ["True", "False"], a: [0] },
    { v: 3, q: "Which three SmartQoS objectives are measured/controlled?", o: ["Disk temperature", "CPU load", "Power usage", "Bandwidth", "IOPS", "Latency"], a: [3, 4, 5] },
    { v: 3, q: "SmartThin supports online capacity expansion.", o: ["True", "False"], a: [0] },
    { v: 3, q: "What is a snapshot according to SNIA?", o: ["Remote mirror", "Encrypted replica", "Full physical backup", "Compressed data copy", "An available copy of specified data at a point in time"], a: [4] },
    { v: 3, q: "What is the main purpose of SmartThin?", o: ["Improve network throughput", "Allocate storage on demand", "Increase RAID redundancy", "Encrypt user data"], a: [1] },
    { v: 3, q: "Which metric is controlled by SmartQoS?", o: ["RAID type", "Encryption level", "File format", "IOPS", "Temperature"], a: [3] },
    { v: 3, q: "SmartMigration ensures service continuity during:", o: ["Data migration", "Backup", "Encryption", "RAID rebuild", "Snapshot"], a: [0] },
    { v: 3, q: "Which are common causes of data loss? (Choose TWO)", o: ["Cloud storage", "Human error", "Hardware failure", "High bandwidth", "Deduplication"], a: [1, 2] },
    { v: 3, q: "Which backup types exist? (Choose THREE)", o: ["Full", "Extension", "Incremental", "Differential", "Elastic"], a: [0, 2, 3] },
    { v: 3, q: "Which environment commonly uses agent-free backup?", o: ["Physical servers", "SAN switches", "Tape libraries", "File systems", "Virtual machines"], a: [4] },
    { v: 3, q: "Backup and disaster recovery are the same thing.", o: ["True", "False"], a: [1] },
    { v: 3, q: "RPO defines acceptable data loss.", o: ["True", "False"], a: [0] },
    { v: 3, q: "Which system focuses on business continuity?", o: ["Snapshot", "Archive", "Disaster Recovery", "Backup", "Deduplication"], a: [2] },
    { v: 3, q: "DR drills are optional and unnecessary.", o: ["True", "False"], a: [1] },

    // --- ВАРИАНТ 4 (32 вопроса) ---
    { v: 4, q: "DR can be implemented at multiple layers.", o: ["True", "False"], a: [0] },
    { v: 4, q: "Which DR mode provides the fastest recovery?", o: ["Tape-based", "Archive recovery", "Active-Active DR", "Active-Passive DR", "Backup-based"], a: [2] },
    { v: 4, q: "What type of disaster is a fire?", o: ["Configuration error", "Human error", "Software disaster", "Logical disaster", "Hard disaster"], a: [4] },
    { v: 4, q: "Which sites are used in DR? (Choose THREE)", o: ["Secondary site", "Test site only", "Primary site", "DR site", "Archive site only"], a: [0, 2, 3] },
    { v: 4, q: "Active-Active DR allows both sites to run services.", o: ["True", "False"], a: [0] },
    { v: 4, q: "Which topology sends backup data over SAN?", o: ["LAN-Based", "Archive", "LAN-Free", "Cloud", "File-level"], a: [2] },
    { v: 4, q: "Which factors affect DR design? (Choose TWO)", o: ["RTO requirements", "Keyboard type", "Screen resolution", "Distance between sites", "Mouse sensitivity"], a: [0, 3] },
    { v: 4, q: "Which are key DR metrics? (Choose THREE)", o: ["FPS", "DPI", "RTO", "RPO", "SLA"], a: [2, 3, 4] },
    { v: 4, q: "Which DR modes exist? (Choose TWO)", o: ["Active-Active", "Active-Passive", "Differential", "Snapshot", "Incremental"], a: [0, 1] },
    { v: 4, q: "Archive systems focus on long-term data storage.", o: ["True", "False"], a: [0] },
    { v: 4, q: "Which characteristics of backup systems? (Choose TWO)", o: ["Zero downtime", "Automatic service takeover", "Data copy storage", "Real-time replication", "Historical data recovery"], a: [2, 4] },
    { v: 4, q: "Which challenges exist in DR implementation? (Choose TWO)", o: ["High cost", "Faster backup", "Complex management", "More storage savings", "Smaller RTO"], a: [0, 2] },
    { v: 4, q: "Which disasters can DR protect against? (Choose THREE)", o: ["Power outages", "File renaming", "Floods", "Earthquakes", "Screen failure"], a: [0, 2, 3] },
    { v: 4, q: "Which are goals of DR systems? (Choose TWO)", o: ["Fast service recovery", "Data deduplication", "Storage compression", "Business continuity", "Data archiving"], a: [0, 3] },
    // Дополнительные вопросы для выравнивания (повторение ключевых тем или ранее не вошедшие)
    { v: 4, q: "Extent is the minimum unit for migration.", o: ["True", "False"], a: [0] },
    { v: 4, q: "Extents are typical operations used in: (Select TWO)", o: ["Parity calculation", "Disk formatting", "Encryption", "Hot data statistics", "Migration"], a: [0, 4] },
    { v: 4, q: "Which components are standard backup storage media? (Select TWO)", o: ["CPU cache", "RAM", "Tape library", "Disk array", "Video card"], a: [2, 3] },
    { v: 4, q: "Source-side deduplication happens:", o: ["On the backup server", "On production host", "On the tape drive", "During network transit"], a: [1] },
    { v: 4, q: "Solutions that replicate data across geographically separate sites provide:", o: ["Local HA", "Geo-redundant DR", "Snapshotting", "RAID protection"], a: [1] },
    { v: 4, q: "Which are standard DR (Disaster Recovery) modes? (Select TWO)", o: ["Active-Active", "Active-Passive", "Differential", "Incremental", "Snapshot"], a: [0, 1] },
    { v: 4, q: "Block Virtualization primarily solves: (Select TWO)", o: ["CPU overload", "Network congestion", "Load imbalance", "Encryption weakness", "Reconstruction risk"], a: [2, 4] },
    { v: 4, q: "RAID 2.0+ uses which concepts? (Select THREE)", o: ["Grains", "Chunks", "CKGs (Chunk Groups)", "Files", "Packets"], a: [0, 1, 2] },
    { v: 4, q: "SAS supports hot swap.", o: ["True", "False"], a: [0] },
    { v: 4, q: "A storage pool primarily manages: (Select THREE)", o: ["Storage resources", "RAID protection", "Network traffic", "Application data", "User permissions"], a: [0, 1, 3] },
    { v: 4, q: "RAID 5 uses: (Select THREE)", o: ["Striping", "Dual parity", "Mirroring", "Distributed parity", "Single disk fault tolerance"], a: [0, 3, 4] },
    { v: 4, q: "RAID 5 suffers from: (Select TWO)", o: ["Write penalty", "High power usage", "Encryption overhead", "No redundancy", "Degraded state risk"], a: [0, 4] },
    { v: 4, q: "NVMe advantages include: (Select THREE)", o: ["Low latency", "Compression", "Encryption", "High bandwidth", "High IOPS"], a: [0, 3, 4] },
    { v: 4, q: "Standard Fibre Channel (FC) topologies include: (Select TWO)", o: ["FC-AL", "Point-to-Point", "Bus", "Ring"], a: [0, 1] },
    { v: 4, q: "SAS vs. parallel SCSI main advantage is:", o: ["Simpler protocol", "Lower power use", "Lower cost", "Higher speed and reliability", "Encryption"], a: [3] },
    { v: 4, q: "NVMe is designed for HDDs.", o: ["True", "False"], a: [1] },
    { v: 4, q: "The technology that allows Fibre Channel (FC) to work over Ethernet is:", o: ["NVMe", "SAS", "PCIe", "FCOE", "RDMA"], a: [3] },
    { v: 4, q: "SAS stands for:", o: ["Smart Access Storage", "Server Attached Storage", "Serial Attached SCSI", "System Access Standard"], a: [2] }
];